# Generated by Django 4.0.5 on 2022-07-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='bio',
            name='hobby',
            field=models.CharField(default='bore', max_length=200),
        ),
    ]
